$background = rgb(000006)
$foreground = rgb(FEEBE6)
$color0 = rgb(000006)
$color1 = rgb(2A3445)
$color2 = rgb(9C4E69)
$color3 = rgb(697861)
$color4 = rgb(AB94CA)
$color5 = rgb(B1C477)
$color6 = rgb(FCC5B8)
$color7 = rgb(F5DAD3)
$color8 = rgb(AC9894)
$color9 = rgb(2A3445)
$color10 = rgb(9C4E69)
$color11 = rgb(697861)
$color12 = rgb(AB94CA)
$color13 = rgb(B1C477)
$color14 = rgb(FCC5B8)
$color15 = rgb(F5DAD3)
