# Lock the screen
listener {
    timeout = 600
    on-timeout = pidof hyprlock || hyprlock && hyprctl switchxkblayout current 0
}

# Turn off screen
listener {
    timeout = 420
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# Suspend the system
#listener {
#    timeout = 600
#    on-timeout = systemctl suspend
#}
