################
### MONITORS ###
################

# Monitors in my current desktop space
# See https://wiki.hyprland.org/Configuring/Monitors/

monitor=DP-2,highres@highrr,0x0,1
monitor=DP-1,highres@highrr,auto-center-left,1,transform,1

##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps. You'll probably like this.
#windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Bind nekoray to a workspace 9
windowrulev2 = monitor DP-1 silent,class:nekoray
windowrulev2 = workspace 9,class:(nekoray)
# workspace = 9,monitor:DP-1

# swaync floating window conf
windowrulev2 = float,class:org.erikreider.swaync
windowrulev2 = move 100%-500 30,class:org.erikreider.swaync

# clipse
windowrulev2 = float,class:clipse # ensure you have a floating window class set if you want this behavior
windowrulev2 = size 622 652,class:clipse # set the size of the window as necessary 

# Bind workspaces to monitors
workspace = 1,monitor:DP-2
workspace = 2,monitor:DP-2
workspace = 3,monitor:DP-2
workspace = 4,monitor:DP-1
workspace = 5,monitor:DP-1
workspace = 6,monitor:DP-1

# hyprshot gui force float
# windowrule = float,title:^(.*Hyprshot.*)$
windowrulev2 = center,title:^(.*Hyprshot.*)$

# battle.net windows to act normal
windowrulev2 = float,class:steam_app_0
windowrulev2 = suppressevent,class:steam_app_0

# Telegram fullscreen media viewer
windowrulev2=float,initialClass:^(org.telegram.desktop|telegramdesktop)$,initialTitle:^(Media viewer)$
windowrulev2=fullscreen,initialClass:^(org.telegram.desktop|telegramdesktop)$,initialTitle:^(Media viewer)$

# firefox PiP to float at start
windowrulev2=opacity 1.0 override 1.0 override,initialClass:firefox,initialTitle:Picture-in-Picture
windowrulev2=float,initialClass:firefox,initialTitle:Picture-in-Picture
windowrulev2=size 800 450,initialClass:firefox,initialTitle:Picture-in-Picture
